CREATE TABLE MI_BOARD
  (
    BOARD_IDX         INTEGER NOT NULL,
    WRITER            VARCHAR2 (10 CHAR) NOT NULL ,
    SUBJECT           VARCHAR2 (100 CHAR) NOT NULL,
    CONTENT           CLOB,
    HIT_CNT           INTEGER NOT NULL,
    DEL_YN            VARCHAR2(1) DEFAULT 'N' NOT NULL,
    DATE_CREATED      DATE NOT NULL,
    DATE_MODIFIED     DATE
  );
ALTER TABLE MI_BOARD ADD CONSTRAINT BOARD_PK PRIMARY KEY ( BOARD_IDX ) ;

CREATE TABLE MI_FILE
  (
    FILE_IDX          INTEGER NOT NULL,
    BOARD_IDX         INTEGER NOT NULL,
    ORI_FILE_NAME     VARCHAR2(260 BYTE) NOT NULL,
    STORED_FILE_NAME  VARCHAR2(36 BYTE) NOT NULL,
    FILE_SIZE         INTEGER NOT NULL,
    DEL_YN            VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL
  );
ALTER TABLE MI_FILE ADD CONSTRAINT FILE_PK PRIMARY KEY ( FILE_IDX ) ;

ALTER TABLE MI_FILE ADD CONSTRAINT BOARD_FILE_FK FOREIGN KEY(BOARD_IDX) REFERENCES MI_BOARD(BOARD_IDX);

--INSERT INTO member VALUES((SELECT NVL(MAX(mno),0)+1 as AIDX FROM member), '이름', '주소', '전화번호', '이메일');
--select /*+ index_desc(BOARD_TBL BOARD_TBL_PK) */ b_num from BOARD_TBL where rownum = 1;

SELECT NVL(MAX(BOARD_IDX),0)+1 FROM MI_BOARD;




